/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplierDisclosuresRouteImport } from './routes/supplier-disclosures'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuestionnairesRouteImport } from './routes/questionnaires'
import { Route as PrintRenderRouteImport } from './routes/print-render'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierDisclosuresIndexRouteImport } from './routes/supplier-disclosures.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as QuestionnairesIndexRouteImport } from './routes/questionnaires.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as SupplierDisclosuresNewRouteImport } from './routes/supplier-disclosures.new'
import { Route as SupplierDisclosuresIdRouteImport } from './routes/supplier-disclosures.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as QuestionnairesNewRouteImport } from './routes/questionnaires.new'
import { Route as QuestionnairesIdRouteImport } from './routes/questionnaires.$id'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as SupplierDisclosuresIdIngestRouteImport } from './routes/supplier-disclosures.$id.ingest'

const SupplierDisclosuresRoute = SupplierDisclosuresRouteImport.update({
  id: '/supplier-disclosures',
  path: '/supplier-disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesRoute = QuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRenderRoute = PrintRenderRouteImport.update({
  id: '/print-render',
  path: '/print-render',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDisclosuresIndexRoute =
  SupplierDisclosuresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SupplierDisclosuresRoute,
  } as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const QuestionnairesIndexRoute = QuestionnairesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionnairesRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const SupplierDisclosuresNewRoute = SupplierDisclosuresNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SupplierDisclosuresRoute,
} as any)
const SupplierDisclosuresIdRoute = SupplierDisclosuresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupplierDisclosuresRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const QuestionnairesNewRoute = QuestionnairesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuestionnairesRoute,
} as any)
const QuestionnairesIdRoute = QuestionnairesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuestionnairesRoute,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRoute,
} as any)
const SupplierDisclosuresIdIngestRoute =
  SupplierDisclosuresIdIngestRouteImport.update({
    id: '/ingest',
    path: '/ingest',
    getParentRoute: () => SupplierDisclosuresIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/print-render': typeof PrintRenderRoute
  '/questionnaires': typeof QuestionnairesRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/supplier-disclosures': typeof SupplierDisclosuresRouteWithChildren
  '/documents/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires/$id': typeof QuestionnairesIdRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/supplier-disclosures/$id': typeof SupplierDisclosuresIdRouteWithChildren
  '/supplier-disclosures/new': typeof SupplierDisclosuresNewRoute
  '/documents/': typeof DocumentsIndexRoute
  '/questionnaires/': typeof QuestionnairesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/supplier-disclosures/': typeof SupplierDisclosuresIndexRoute
  '/supplier-disclosures/$id/ingest': typeof SupplierDisclosuresIdIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/audit': typeof AuditRoute
  '/print-render': typeof PrintRenderRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires/$id': typeof QuestionnairesIdRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/supplier-disclosures/$id': typeof SupplierDisclosuresIdRouteWithChildren
  '/supplier-disclosures/new': typeof SupplierDisclosuresNewRoute
  '/documents': typeof DocumentsIndexRoute
  '/questionnaires': typeof QuestionnairesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/supplier-disclosures': typeof SupplierDisclosuresIndexRoute
  '/supplier-disclosures/$id/ingest': typeof SupplierDisclosuresIdIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/print-render': typeof PrintRenderRoute
  '/questionnaires': typeof QuestionnairesRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/supplier-disclosures': typeof SupplierDisclosuresRouteWithChildren
  '/documents/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires/$id': typeof QuestionnairesIdRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/supplier-disclosures/$id': typeof SupplierDisclosuresIdRouteWithChildren
  '/supplier-disclosures/new': typeof SupplierDisclosuresNewRoute
  '/documents/': typeof DocumentsIndexRoute
  '/questionnaires/': typeof QuestionnairesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/supplier-disclosures/': typeof SupplierDisclosuresIndexRoute
  '/supplier-disclosures/$id/ingest': typeof SupplierDisclosuresIdIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/audit'
    | '/documents'
    | '/print-render'
    | '/questionnaires'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/supplier-disclosures'
    | '/documents/$id'
    | '/onboarding/$step'
    | '/questionnaires/$id'
    | '/questionnaires/new'
    | '/reports/$id'
    | '/supplier-disclosures/$id'
    | '/supplier-disclosures/new'
    | '/documents/'
    | '/questionnaires/'
    | '/reports/'
    | '/supplier-disclosures/'
    | '/supplier-disclosures/$id/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/audit'
    | '/print-render'
    | '/settings'
    | '/sources'
    | '/documents/$id'
    | '/onboarding/$step'
    | '/questionnaires/$id'
    | '/questionnaires/new'
    | '/reports/$id'
    | '/supplier-disclosures/$id'
    | '/supplier-disclosures/new'
    | '/documents'
    | '/questionnaires'
    | '/reports'
    | '/supplier-disclosures'
    | '/supplier-disclosures/$id/ingest'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/audit'
    | '/documents'
    | '/print-render'
    | '/questionnaires'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/supplier-disclosures'
    | '/documents/$id'
    | '/onboarding/$step'
    | '/questionnaires/$id'
    | '/questionnaires/new'
    | '/reports/$id'
    | '/supplier-disclosures/$id'
    | '/supplier-disclosures/new'
    | '/documents/'
    | '/questionnaires/'
    | '/reports/'
    | '/supplier-disclosures/'
    | '/supplier-disclosures/$id/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AuditRoute: typeof AuditRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  PrintRenderRoute: typeof PrintRenderRoute
  QuestionnairesRoute: typeof QuestionnairesRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  SupplierDisclosuresRoute: typeof SupplierDisclosuresRouteWithChildren
  OnboardingStepRoute: typeof OnboardingStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplier-disclosures': {
      id: '/supplier-disclosures'
      path: '/supplier-disclosures'
      fullPath: '/supplier-disclosures'
      preLoaderRoute: typeof SupplierDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires': {
      id: '/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof QuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-render': {
      id: '/print-render'
      path: '/print-render'
      fullPath: '/print-render'
      preLoaderRoute: typeof PrintRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-disclosures/': {
      id: '/supplier-disclosures/'
      path: '/'
      fullPath: '/supplier-disclosures/'
      preLoaderRoute: typeof SupplierDisclosuresIndexRouteImport
      parentRoute: typeof SupplierDisclosuresRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/questionnaires/': {
      id: '/questionnaires/'
      path: '/'
      fullPath: '/questionnaires/'
      preLoaderRoute: typeof QuestionnairesIndexRouteImport
      parentRoute: typeof QuestionnairesRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/supplier-disclosures/new': {
      id: '/supplier-disclosures/new'
      path: '/new'
      fullPath: '/supplier-disclosures/new'
      preLoaderRoute: typeof SupplierDisclosuresNewRouteImport
      parentRoute: typeof SupplierDisclosuresRoute
    }
    '/supplier-disclosures/$id': {
      id: '/supplier-disclosures/$id'
      path: '/$id'
      fullPath: '/supplier-disclosures/$id'
      preLoaderRoute: typeof SupplierDisclosuresIdRouteImport
      parentRoute: typeof SupplierDisclosuresRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/questionnaires/new': {
      id: '/questionnaires/new'
      path: '/new'
      fullPath: '/questionnaires/new'
      preLoaderRoute: typeof QuestionnairesNewRouteImport
      parentRoute: typeof QuestionnairesRoute
    }
    '/questionnaires/$id': {
      id: '/questionnaires/$id'
      path: '/$id'
      fullPath: '/questionnaires/$id'
      preLoaderRoute: typeof QuestionnairesIdRouteImport
      parentRoute: typeof QuestionnairesRoute
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/supplier-disclosures/$id/ingest': {
      id: '/supplier-disclosures/$id/ingest'
      path: '/ingest'
      fullPath: '/supplier-disclosures/$id/ingest'
      preLoaderRoute: typeof SupplierDisclosuresIdIngestRouteImport
      parentRoute: typeof SupplierDisclosuresIdRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface QuestionnairesRouteChildren {
  QuestionnairesIdRoute: typeof QuestionnairesIdRoute
  QuestionnairesNewRoute: typeof QuestionnairesNewRoute
  QuestionnairesIndexRoute: typeof QuestionnairesIndexRoute
}

const QuestionnairesRouteChildren: QuestionnairesRouteChildren = {
  QuestionnairesIdRoute: QuestionnairesIdRoute,
  QuestionnairesNewRoute: QuestionnairesNewRoute,
  QuestionnairesIndexRoute: QuestionnairesIndexRoute,
}

const QuestionnairesRouteWithChildren = QuestionnairesRoute._addFileChildren(
  QuestionnairesRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SupplierDisclosuresIdRouteChildren {
  SupplierDisclosuresIdIngestRoute: typeof SupplierDisclosuresIdIngestRoute
}

const SupplierDisclosuresIdRouteChildren: SupplierDisclosuresIdRouteChildren = {
  SupplierDisclosuresIdIngestRoute: SupplierDisclosuresIdIngestRoute,
}

const SupplierDisclosuresIdRouteWithChildren =
  SupplierDisclosuresIdRoute._addFileChildren(
    SupplierDisclosuresIdRouteChildren,
  )

interface SupplierDisclosuresRouteChildren {
  SupplierDisclosuresIdRoute: typeof SupplierDisclosuresIdRouteWithChildren
  SupplierDisclosuresNewRoute: typeof SupplierDisclosuresNewRoute
  SupplierDisclosuresIndexRoute: typeof SupplierDisclosuresIndexRoute
}

const SupplierDisclosuresRouteChildren: SupplierDisclosuresRouteChildren = {
  SupplierDisclosuresIdRoute: SupplierDisclosuresIdRouteWithChildren,
  SupplierDisclosuresNewRoute: SupplierDisclosuresNewRoute,
  SupplierDisclosuresIndexRoute: SupplierDisclosuresIndexRoute,
}

const SupplierDisclosuresRouteWithChildren =
  SupplierDisclosuresRoute._addFileChildren(SupplierDisclosuresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AuditRoute: AuditRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  PrintRenderRoute: PrintRenderRoute,
  QuestionnairesRoute: QuestionnairesRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  SupplierDisclosuresRoute: SupplierDisclosuresRouteWithChildren,
  OnboardingStepRoute: OnboardingStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
