packages:
  - desktop
  - cloud/web
allowBuilds:
  '@google/genai': false
  better-sqlite3: true
  electron: true
  electron-winstaller: false
  esbuild: true
  protobufjs: false
  sharp: true
  workerd: true
