import { publicKeyFromRawBytes } from './license-service.js';

/**
 * Ed25519 public key for verifying license JWTs.
 *
 * **DEVELOPMENT PLACEHOLDER** — the real production key is generated by
 * carbonbook-cloud and embedded at release time. Until Phase 4 sub-project
 * G (cloud impl) ships, Task 5 of sub-project A regenerates a dev keypair
 * locally and rewrites the hex below; the matching private key lives at
 * `scripts/dev/license-keypair/private.pem` and powers
 * `scripts/issue-dev-license.mjs`.
 *
 * Replacing this constant + the matching cloud-side private key + cutting a
 * release is what migrates the install base from dev keys to prod.
 *
 * Sanity guard: `loadLicensePublicKey()` throws if the hex is all-zero so a
 * release accidentally shipped with the placeholder is loud-failing on
 * first launch rather than silently accepting any forged JWT (a `null`
 * signature against a degenerate key would also fail the cryptographic
 * verify, but the explicit guard surfaces the misconfiguration earlier).
 */
const DEV_PUBLIC_KEY_HEX =
  '0000000000000000000000000000000000000000000000000000000000000000';

export function loadLicensePublicKey() {
  if (/^0+$/.test(DEV_PUBLIC_KEY_HEX)) {
    // Sub-project A Task 5 generates the real dev key and rewrites this
    // constant. If you're reading this in production, the build pipeline
    // forgot to substitute the prod key — bail rather than ship a broken
    // verifier that would reject every legitimate license.
    throw new Error(
      'license public key not initialised — see src/main/services/license-public-key.ts',
    );
  }
  const bytes = Buffer.from(DEV_PUBLIC_KEY_HEX, 'hex');
  return publicKeyFromRawBytes(bytes);
}
