import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ExcelParser } from '@main/excel/parser';
import { describe, expect, it } from 'vitest';

/**
 * Integration test for the sample outbound-import fixture
 * (`tests/e2e/fixtures/sample-customer-questionnaire-2025.xlsx`, generated by
 * `scripts/make-sample-questionnaire.mjs`).
 *
 * The fixture stands in for a customer / rating-agency GHG questionnaire that a
 * user uploads in the 披露填报 flow. This test runs the REAL `ExcelParser.parse`
 * (the same parser the import handler injects as `excelParse`) against it, so we
 * verify the fixture is well-formed for the import pipeline — and the test fails
 * loudly if the generator ever drifts. (The LLM question-extraction step that
 * consumes these cells is non-deterministic, so it's exercised manually / in the
 * Playwright upload flow, not here.)
 */
const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(
  __dirname,
  '..',
  '..',
  'e2e',
  'fixtures',
  'sample-customer-questionnaire-2025.xlsx',
);

describe('sample customer questionnaire fixture (outbound import)', () => {
  it('parses through the real ExcelParser with the expected questions + blank answer cells', async () => {
    const cells = await ExcelParser.parse(readFileSync(FIXTURE));

    // Single sheet, all cells belong to it.
    expect(cells.length).toBeGreaterThan(0);
    expect(cells.every((c) => c.sheet === '碳排放披露问卷')).toBe(true);

    // 14 numbered questions live in column A (1-based); section/title/header rows
    // are text, so the numeric col-A cells are exactly the questions.
    const numberedQuestions = cells.filter((c) => c.col === 1 && typeof c.value === 'number');
    expect(numberedQuestions).toHaveLength(14);

    // The question text the extractor reads is all present (stable substrings).
    const text = cells.map((c) => String(c.value ?? '')).join('\n');
    for (const marker of [
      '报告主体名称',
      '组织边界',
      'Scope 1',
      'location-based',
      'market-based',
      '外购电力消耗',
      '可再生能源电力占比',
      'Scope 3',
      '减排目标',
      '核查状态',
      '核算方法',
    ]) {
      expect(text, `expected fixture to contain "${marker}"`).toContain(marker);
    }

    // The Response column (C / col 3) is blank for every question row (row >= 4).
    // The parser only returns non-empty cells, so there are none — those are the
    // answer slots the app maps each question to and writes back into on export.
    expect(cells.filter((c) => c.col === 3 && c.row >= 4)).toHaveLength(0);
  });
});
