/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as QuestionnairesRouteImport } from './routes/questionnaires'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionnairesNewRouteImport } from './routes/questionnaires_.new'
import { Route as QuestionnairesIdRouteImport } from './routes/questionnaires_.$id'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as DocumentsIdRouteImport } from './routes/documents_.$id'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesRoute = QuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesNewRoute = QuestionnairesNewRouteImport.update({
  id: '/questionnaires_/new',
  path: '/questionnaires/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdRoute = QuestionnairesIdRouteImport.update({
  id: '/questionnaires_/$id',
  path: '/questionnaires/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents_/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/documents': typeof DocumentsRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/sources': typeof SourcesRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires/$id': typeof QuestionnairesIdRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/documents': typeof DocumentsRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/sources': typeof SourcesRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires/$id': typeof QuestionnairesIdRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/documents': typeof DocumentsRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/sources': typeof SourcesRoute
  '/documents_/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires_/$id': typeof QuestionnairesIdRoute
  '/questionnaires_/new': typeof QuestionnairesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/documents'
    | '/questionnaires'
    | '/sources'
    | '/documents/$id'
    | '/onboarding/$step'
    | '/questionnaires/$id'
    | '/questionnaires/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/documents'
    | '/questionnaires'
    | '/sources'
    | '/documents/$id'
    | '/onboarding/$step'
    | '/questionnaires/$id'
    | '/questionnaires/new'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/documents'
    | '/questionnaires'
    | '/sources'
    | '/documents_/$id'
    | '/onboarding/$step'
    | '/questionnaires_/$id'
    | '/questionnaires_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  DocumentsRoute: typeof DocumentsRoute
  QuestionnairesRoute: typeof QuestionnairesRoute
  SourcesRoute: typeof SourcesRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
  QuestionnairesIdRoute: typeof QuestionnairesIdRoute
  QuestionnairesNewRoute: typeof QuestionnairesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires': {
      id: '/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof QuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires_/new': {
      id: '/questionnaires_/new'
      path: '/questionnaires/new'
      fullPath: '/questionnaires/new'
      preLoaderRoute: typeof QuestionnairesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires_/$id': {
      id: '/questionnaires_/$id'
      path: '/questionnaires/$id'
      fullPath: '/questionnaires/$id'
      preLoaderRoute: typeof QuestionnairesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents_/$id': {
      id: '/documents_/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  DocumentsRoute: DocumentsRoute,
  QuestionnairesRoute: QuestionnairesRoute,
  SourcesRoute: SourcesRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  OnboardingStepRoute: OnboardingStepRoute,
  QuestionnairesIdRoute: QuestionnairesIdRoute,
  QuestionnairesNewRoute: QuestionnairesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
