/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuestionnairesRouteImport } from './routes/questionnaires'
import { Route as PrintRenderRouteImport } from './routes/print-render'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIdRouteImport } from './routes/reports_.$id'
import { Route as QuestionnairesNewRouteImport } from './routes/questionnaires_.new'
import { Route as QuestionnairesIdRouteImport } from './routes/questionnaires_.$id'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as DocumentsIdRouteImport } from './routes/documents_.$id'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesRoute = QuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRenderRoute = PrintRenderRouteImport.update({
  id: '/print-render',
  path: '/print-render',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports_/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesNewRoute = QuestionnairesNewRouteImport.update({
  id: '/questionnaires_/new',
  path: '/questionnaires/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdRoute = QuestionnairesIdRouteImport.update({
  id: '/questionnaires_/$id',
  path: '/questionnaires/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents_/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRoute
  '/print-render': typeof PrintRenderRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires/$id': typeof QuestionnairesIdRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRoute
  '/print-render': typeof PrintRenderRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires/$id': typeof QuestionnairesIdRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRoute
  '/print-render': typeof PrintRenderRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/documents_/$id': typeof DocumentsIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/questionnaires_/$id': typeof QuestionnairesIdRoute
  '/questionnaires_/new': typeof QuestionnairesNewRoute
  '/reports_/$id': typeof ReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/audit'
    | '/documents'
    | '/print-render'
    | '/questionnaires'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/documents/$id'
    | '/onboarding/$step'
    | '/questionnaires/$id'
    | '/questionnaires/new'
    | '/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/audit'
    | '/documents'
    | '/print-render'
    | '/questionnaires'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/documents/$id'
    | '/onboarding/$step'
    | '/questionnaires/$id'
    | '/questionnaires/new'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/audit'
    | '/documents'
    | '/print-render'
    | '/questionnaires'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/documents_/$id'
    | '/onboarding/$step'
    | '/questionnaires_/$id'
    | '/questionnaires_/new'
    | '/reports_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AuditRoute: typeof AuditRoute
  DocumentsRoute: typeof DocumentsRoute
  PrintRenderRoute: typeof PrintRenderRoute
  QuestionnairesRoute: typeof QuestionnairesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
  QuestionnairesIdRoute: typeof QuestionnairesIdRoute
  QuestionnairesNewRoute: typeof QuestionnairesNewRoute
  ReportsIdRoute: typeof ReportsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires': {
      id: '/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof QuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-render': {
      id: '/print-render'
      path: '/print-render'
      fullPath: '/print-render'
      preLoaderRoute: typeof PrintRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports_/$id': {
      id: '/reports_/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires_/new': {
      id: '/questionnaires_/new'
      path: '/questionnaires/new'
      fullPath: '/questionnaires/new'
      preLoaderRoute: typeof QuestionnairesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires_/$id': {
      id: '/questionnaires_/$id'
      path: '/questionnaires/$id'
      fullPath: '/questionnaires/$id'
      preLoaderRoute: typeof QuestionnairesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents_/$id': {
      id: '/documents_/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AuditRoute: AuditRoute,
  DocumentsRoute: DocumentsRoute,
  PrintRenderRoute: PrintRenderRoute,
  QuestionnairesRoute: QuestionnairesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  OnboardingStepRoute: OnboardingStepRoute,
  QuestionnairesIdRoute: QuestionnairesIdRoute,
  QuestionnairesNewRoute: QuestionnairesNewRoute,
  ReportsIdRoute: ReportsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
